import Head from "next/head";
import Image from "next/image";
import products from "../products.json";

export default function Home() {
  console.log(products.data);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {products.data.map((product) => (
        <div key={product.id} className="p-[24px] text-[24px] ">
          <div className="flex">
            <div className="flex-1 max-w-[50px] mr-[25px]">
              <img src="" />
            </div>
            <div className="flex-1">
              {product.attributes.name} {product.attributes.price}
            </div>
          </div>
        </div>
      ))}
    </div>
  );
}
