import Head from "next/head";
import Image from "next/image";
import projects from "../projects.json";
import { fromImgToUrl } from "../utils/urls";
import Link from "next/link";

export default function Home() {
  console.log(projects.data);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {projects.data.map((product) => (
        <div key={product.id} className="p-[24px] text-[24px] ">
          <Link href={`/projects/${product.attributes.slug}`}>
            <a>
              <div className="flex">
                <div className="flex-1 max-w-[50px] mr-[25px]">
                  <img
                    src={fromImgToUrl(product.attributes.image.data.attributes)}
                    className="max-w-[100%]"
                  />
                </div>
                <div className="flex-1">
                  {product.attributes.name} {product.attributes.price}
                </div>
              </div>
            </a>
          </Link>
        </div>
      ))}
    </div>
  );
}
